# Generated by Django 6.0.5 on 2026-05-28 10:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SlamBook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(help_text='Unique slug for public slam book link', max_length=255, unique=True)),
                ('title', models.CharField(help_text='Title of the slam book', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Slam book bio or introduction', null=True)),
                ('cover_image', models.ImageField(blank=True, help_text='Optional scrapbook cover image', null=True, upload_to='covers/')),
                ('theme', models.CharField(default='School Notebook', help_text='Themes: School Notebook, Y2K, Diary, Polaroid, Dark Academia', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slambooks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SlamEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('anonymous_name', models.CharField(blank=True, help_text='Creator name if guest/anonymous', max_length=255, null=True)),
                ('answers', models.JSONField(help_text='Key-value mapping of answers where key is question UUID or question text')),
                ('theme', models.CharField(default='School Notebook', help_text='Selected layout theme for this page', max_length=100)),
                ('image_url', models.ImageField(blank=True, help_text='Optional uploaded picture or polaroid sticker', null=True, upload_to='entries/')),
                ('ip_hash', models.CharField(blank=True, help_text='SHA256 hash of submitter IP address for rate-limiting', max_length=64, null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Browser client user-agent', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, help_text='Null if anonymous submission', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries_written', to=settings.AUTH_USER_MODEL)),
                ('slam_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='slambooks.slambook')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField(help_text='Reason for reporting this entry')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='slambooks.slamentry')),
            ],
        ),
        migrations.CreateModel(
            name='SlamQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.TextField(help_text='Custom question content')),
                ('order', models.IntegerField(default=0, help_text='Position of the question card')),
                ('slam_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='slambooks.slambook')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
