# Generated by Django 6.0.5 on 2026-05-28 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slambooks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slamentry',
            name='ip_address',
            field=models.CharField(blank=True, help_text='Raw IP address of the submitter (admin view only)', max_length=100, null=True),
        ),
    ]
